esphome:
  name: comfoair
  platform: ESP32
  board: esp32doit-devkit-v1
  includes:
    - comfoair.h
  platformio_options:
    platform: espressif32@1.11.0
    platform_packages: |-4
      
          framework-arduinoespressif32 @ https://github.com/pauln/arduino-esp32.git#solo-no-mac-crc/1.0.4

wifi:
  ssid: 'your-wifi-ssid-here'
  password: 'put-your-wifi-password-here'

# Enable Home Assistant API
api:
  password: 'set-an-api-password-here'

custom_component:
- id: comfoair
  lambda: |-
    auto comfoaircomponent = new ComfoAirComponent();
    App.register_component(comfoaircomponent);
    return {comfoaircomponent};
