esphome:
  name: comfoair
  platform: ESP8266
  board: esp01_1m
  includes:
    - comfoair.h

wifi:
  ssid: 'your-wifi-ssid-here'
  password: 'put-your-wifi-password-here'

# Disable uart logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  password: 'set-an-api-password-here'

ota:

sensor:
binary_sensor:

uart:
  id: uart_bus
  baud_rate: 9600
  tx_pin: TX
  rx_pin: RX 

climate:
- platform: custom
  lambda: |-
    auto ca = new esphome::comfoair::ComfoAirComponent(id(uart_bus));
    App.register_component(ca);
    App.register_climate(ca);
    return {ca};

  climates:
    - name: "put-yout-comfoair-name-here"
